### ISSUE TITLE
Builds failing likely due to Python 2 support ending

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/docker-ubuntu1604-ansible#11]
Builds failing when pip tries installing:

```
Traceback (most recent call last):
  File "get-pip.py", line 24244, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpw8qqxl/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by geerlingguy** [comment]
Testing a fix just switching everything over to Python 3. Might break some builds... but better than having this image just rot forever...

**Comment by geerlingguy** [comment]
Well, Python 3 caused a new can of worms, which I didn't want to jump around resolving for an OS that's going to be unsupported in a few months...

Using https://bootstrap.pypa.io/2.7/get-pip.py instead. Fixes it.
